openapi: 3.0.1
info:
  version: 0.0.1
  title: Shurara
servers:
- url: http://localhost:8080/v1
paths:
  /posts:
    get:
      summary: Get recent posts globally
      tags:
      - posts
      responses:
        "200":
          description: OK
    post:
      summary: Create a post
      tags:
      - posts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPostRequestBody"
      responses:
        "201":
          description: OK
  /posts/{slug}:
    get:
      summary: Get an post
      tags:
      - posts
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      summary: Delete a post
      tags:
      - posts
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /posts/{slug}/comments:
    get:
      summary: Get comments for post
      tags:
      - comments
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MultipleCommentsResponse"
    post:
      summary: Create a comment for a post
      tags:
      - comments
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCommentRequestBody"
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SingleCommentResponse"
  /posts/{slug}/comments/{id}:
    delete:
      summary: Delete a comment for a post
      tags:
      - comments
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
components:
  schemas:
    NewPostRequestBody:
      type: object
    Comment:
      type: object
      properties:
        id:
          type: integer
        body:
          type: string
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
    NewCommentRequestBody:
      type: object
      properties:
        body:
          type: string
    SingleCommentResponse:
      type: object
      properties:
        comment:
          $ref: "#/components/schemas/Comment"
      required:
      - comment
    MultipleCommentsResponse:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"
      required:
      - comments
tags:
- name: posts
- name: comments
